### ISSUE TITLE
FORMAT ERROR: "Error -112\nUnknown call

### ISSUE THREAD

**Issue by jimcortez** [dirkmoors/pyejabberd#11]
Hey there! Thanks for putting this library together!

I am attempting to use this agains ejabberd 15.02 and am running into an error once the server receives a register request. I have used an admin account for auth, then attempting to register a new user.

Relevent logs:
Server:

> 2015-07-28 21:51:57.459 [debug] <0.2849.0>@ejabberd_http:init:153 S: [{[],ejabberd_xmlrpc}]
> 2015-07-28 21:51:57.459 [info] <0.2849.0>@ejabberd_http:init:157 started: {gen_tcp,#Port<0.22749>}
> 2015-07-28 21:51:57.460 [debug] <0.2849.0>@ejabberd_http:process_header:279 (#Port<0.22749>) http query: 'POST' <<"/">>
> 2015-07-28 21:51:57.460 [debug] <0.2849.0>@ejabberd_http:extract_path_query:399 client data: <<"<?xml version='1.0'?>\n<methodCall>\n<methodName>register</methodName>\n<params>\n<param>\n<value><struct>\n<member>\n<name>password</name>\n<value><string>redacted_auth_passwd</string></value>\n</member>\n<member>\n<name>user</name>\n<value><string>redacted_auth_username</string></value>\n</member>\n<member>\n<name>server</name>\n<value><string>redacted_server_hostname</string></value>\n</member>\n</struct></value>\n</param>\n<param>\n<value><struct>\n<member>\n<name>host</name>\n<value><string>redacted_server_hostname</string></value>\n</member>\n<member>\n<name>password</name>\n<value><string>redacted_new_passwd</string></value>\n</member>\n<member>\n<name>user</name>\n<value><string>redacted_new_username</string></value>\n</member>\n</struct></value>\n</param>\n</params>\n</methodCall>\n">>
> 2015-07-28 21:51:57.460 [debug] <0.2849.0>@ejabberd_http:process:357 [] matches []
> 2015-07-28 21:51:57.464 [debug] <0.2849.0>@ejabberd_xmlrpc:process:244 got XML-RPC request: {call,register,[{struct,[{password,<<"redacted_auth_passwd">>},{user,<<"redacted_auth_username">>},{server,<<"redacted_server_hostname">>}]},{struct,[{host,<<"redacted_server_hostname">>},{password,<<"redacted_new_passwd">>},{user,<<"redacted_new_username">>}]}]}
> 2015-07-28 21:51:57.464 [warning] <0.2849.0>@ejabberd_xmlrpc:build_fault_response:380 FORMAT ERROR: "Error -112\nUnknown call: {call,register,\n                    [{struct,[{password,<<\"redacted_auth_passwd\">>},\n                              {user,<<\"redacted_auth_username\">>},\n                              {server,<<\"redacted_server_hostname\">>}]},\n                     {struct,[{host,<<\"redacted_server_hostname\">>},\n                              {password,<<\"redacted_new_passwd\">>},\n                              {user,<<\"redacted_new_username\">>}]}]}" []

Client Debug:

> ===> register(host=redacted_server_hostname, password=redacted_new_passwd, user=redacted_new_username)
> send: "POST / HTTP/1.1\r\nHost: redacted_server_hostname:4560\r\nAccept-Encoding: gzip\r\nUser-Agent: xmlrpclib.py/1.0.1 (by www.pythonware.com)\r\nContent-Type: text/xml\r\nContent-Length: 744\r\n\r\n<?xml version='1.0'?>\n<methodCall>\n<methodName>register</methodName>\n<params>\n<param>\n<value><struct>\n<member>\n<name>password</name>\n<value><string>redacted_auth_passwd</string></value>\n</member>\n<member>\n<name>user</name>\n<value><string>redacted_auth_username</string></value>\n</member>\n<member>\n<name>server</name>\n<value><string>redacted_server_hostname</string></value>\n</member>\n</struct></value>\n</param>\n<param>\n<value><struct>\n<member>\n<name>host</name>\n<value><string>redacted_server_hostname</string></value>\n</member>\n<member>\n<name>password</name>\n<value><string>redacted_new_passwd</string></value>\n</member>\n<member>\n<name>user</name>\n<value><string>redacted_new_username</string></value>\n</member>\n</struct></value>\n</param>\n</params>\n</methodCall>\n"
> reply: 'HTTP/1.1 200 OK\r\n'
> header: Content-Length: 810
> header: Content-Type: text/xml
> body: '<?xml version="1.0"?><methodResponse><fault><value><struct><member><name>faultCode</name><value><int>-112</int></value></member><member><name>faultString</name><value><string>Error -112\nUnknown call: {call,register,\n                    [{struct,[{password,&lt;&lt;&quot;redacted_auth_passwd&quot;&gt;&gt;},\n                              {user,&lt;&lt;&quot;redacted_auth_username&quot;&gt;&gt;},\n                              {server,&lt;&lt;&quot;redacted_server_hostname&quot;&gt;&gt;}]},\n                     {struct,[{host,&lt;&lt;&quot;redacted_server_hostname&quot;&gt;&gt;},\n                              {password,&lt;&lt;&quot;redacted_new_passwd&quot;&gt;&gt;},\n                              {user,&lt;&lt;&quot;redacted_new_username&quot;&gt;&gt;}]}]}</string></value></member></struct></value></fault></methodResponse>'
> ERROR:ivee.server:Exception on /devices/add [POST]
> Traceback (most recent call last):
>   <snip>
>   File "/Users/jecortez/workspace/redacted_auth_username/venv/lib/python2.7/site-packages/pyejabberd/client.py", line 160, in register
>     return self._call_api(definitions.Register, user=user, host=host, password=password)
>   File "/Users/jecortez/workspace/redacted_auth_username/venv/lib/python2.7/site-packages/pyejabberd/client.py", line 384, in _call_api
>     response = method(self.auth, arguments)
>   File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1233, in __call__
>     return self.__send(self.__name, args)
>   File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1591, in __request
>     verbose=self.__verbose
>   File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1273, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1306, in single_request
>     return self.parse_response(response)
>   File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
>     return u.close()
>   File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 794, in close
>     raise Fault(**self._stack[0])
> Fault: <Fault -112: 'Error -112\nUnknown call: {call,register,\n                    [{struct,[{password,<<"redacted_auth_passwd">>},\n                              {user,<<"redacted_auth_username">>},\n                              {server,<<"redacted_server_hostname">>}]},\n                     {struct,[{host,<<"redacted_server_hostname">>},\n                              {password,<<"redacted_new_passwd">>},\n                              {user,<<"redacted_new_username">>}]}]}'>

Any ideas?

**Comment by jimcortez** [comment]
This was a server configuration issue. Here is how I fixed it:

``` yaml
acl:
  ...
  xmlrpc_users:
    user:
      - "admin": "example.com"

access:
  ...
  xmlrpc_access:
    xmlrpc_users: allow

listen:
  ...
  -
    port: 4560
    module: ejabberd_xmlrpc
    access_commands:
      xmlrpc_access:
        commands: all
        options: {}
```

**Comment by dirkmoors** [comment]
Awesome, thank you for your contribution, and for sharing your fix, @jimcortez !
